apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-novalinx
spec:
  displayName: Novalinx 主题
  author:
    name: weiyong
    website: https://github.com/imswy/halo-theme-novalinx
  description: A development starter theme with Vite Ecosystem for Halo
  logo: https://www.halo.run/logo
  homepage: https://github.com/imswy/halo-theme-novalinx#readme
  repo: https://github.com/imswy/halo-theme-novalinx
  issues: https://github.com/imswy/halo-theme-novalinx/issues
  settingName: "halo-theme-novalinx-setting"
  configMapName: "halo-theme-novalinx-configMap"
  version: "1.0.0"
  requires: "2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/halo-theme-novalinx/blob/main/LICENSE"
